# travis need to have provided language type to start proper build process.
language: java

sudo: required # for docker

# The Travis CI environment provides Oracle JDK 7 (default),
# so we need to force use jdk8 instead.
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
  - docker-compose --file docker-compose-ci.yml up &
  # produces docker images and run integration tests.
  - mvn verify
    # produces quality metrics for sonarqube.com
  - mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login="$SONAR_TOKEN" -Dsonar.projectKey=auctionfinderBackend

after_success:
  # push application image to docker registry
  # initially will start to push from master
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push virtum/auctionfinderBackend;
    fi


# support for docker
services:
- docker